# gcc 10.4.0 is broken due and fixed by https://github.com/gcc-mirror/gcc/commit/32bbf76e4345a7961445b86a7cfccffa8a287fc1
c_compiler_version:    # [linux]
- '10.3.0'             # [linux]
cxx_compiler_version:  # [linux]
- '10.3.0'             # [linux]
